{{- if .Values.bitcoinCashNodeChipnet.enable }}
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-cash-node-chipnet-service
  labels:
    app: bitcoin-cash-node-chipnet
    {{- include "chaingraph.labels" . | nindent 4 }}
spec:
  ports:
    - name: chipnet-p2p
      port: 48333
  type: ClusterIP
  selector:
    app: bitcoin-cash-node-chipnet
{{- end }}
