apiVersion: v1
kind: Service
metadata:
  name: hasura-service
  labels:
    app: hasura
    {{- include "chaingraph.labels" . | nindent 4 }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.hasura.servicePort }}
    targetPort: 8080
{{- if .Values.useDevelopmentVolumes }}
    nodePort: 31933
{{- end }}
  selector:
    app: hasura
  externalTrafficPolicy: Local
{{- if .Values.hasura.useLoadBalancer }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
