name: Lint, Build, and Test Chaingraph
on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: chaingraph
          POSTGRES_USER: chaingraph
          POSTGRES_PASSWORD: very_insecure_postgres_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test
      - run: yarn cov:lcov
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Save E2E test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-test-log
          path: data/chaingraph/log-e2e.ndjson
