name: 'Build Image: bitcoin-cash-node'
on:
  push:
    paths:
      - 'images/bitcoin-cash-node/**'
      - '!images/bitcoin-cash-node/readme.md'
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version
        run: |
          echo "::set-output name=version::$(grep -F 'ENV BITCOIN_VERSION' images/bitcoin-cash-node/Dockerfile | grep -oE '[0-9.]+')"
        id: get_version
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build, tag, push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: images/bitcoin-cash-node
          push: true
          tags: chaingraph/bitcoin-cash-node:latest,chaingraph/bitcoin-cash-node:${{ steps.get_version.outputs.version }}
      - name: Echo image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
