name: 'Build Image: hasura'
on:
  push:
    paths:
      - 'images/hasura/**'
      - '!images/hasura/readme.md'
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tag
        run: |
          echo "::set-output name=commit::$(git rev-parse --short HEAD)"
        id: get_tag
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build, tag, push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: images/hasura
          push: true
          tags: chaingraph/hasura:latest,chaingraph/hasura:${{ steps.get_tag.outputs.commit }}
      - name: Echo image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

